Sunami-Django-Old/accounts/urls.py
from django.conf.urls import patterns, url
from accounts.views import SignUpView, LoginView, LogoutView, ConfirmView, PasswordResetView, IForgotView

urlpatterns = patterns('',

    url(r'^login/$', LoginView.as_view(), name = 'login'),
    url(r'^signup/$', SignUpView.as_view(), name = 'signup'),
    url(r'^logout/$', LogoutView.as_view(), name = 'logout'),
    url(r'^iforgot/$', IForgotView.as_view(), name = 'iforgot'),
    url(r'^confirm/(?P<confirmation_code>[a-zA-Z0-9]+)/(?P<username>[a-zA-Z0-9]+)/$', ConfirmView.as_view(), name = 'confirm'),
    url(r'^passreset/(?P<confirmation_code>[a-zA-Z0-9]+)/(?P<username>[a-zA-Z0-9]+)/$', PasswordResetView.as_view(), name = 'passreset'),
	
	)

Sunami-Django-Old/sunami/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from sunami.views import IndexView

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', include('accounts.urls', namespace = 'accounts')),
    url(r'^$', IndexView.as_view(), name = 'index'),
 
) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Sunami-Django-Old/accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

# Model for user profiles
class UserProfile(models.Model):
	user = models.OneToOneField(User)

	confirmation_code = models.CharField('Confirmation Code', max_length = 50, default = '')
	is_password_reset = models.BooleanField('Password Reset Active', default = False)
	status = models.CharField('User Status', max_length = 500, blank = True)
	display_picture = models.ImageField('User Display Picture', upload_to = 'display_pictures', blank = True)

	def __str__(self):
		return self.user.username

Sunami-Django-Old/accounts/forms.py
from django import forms, template
from django.contrib.auth.models import User
from accounts.models import UserProfile

class UserForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(UserForm, self).__init__(*args, **kwargs)

		self.fields['email'].required = True

	class Meta:
		model = User
		fields = ('username', 'email', 'password')
		widgets = {
			'username' : forms.TextInput(attrs = {'placeholder' : 'Username'}),
			'password' : forms.PasswordInput(attrs = {'placeholder' : 'Password'}),
			'email' : forms.EmailInput(attrs = {'placeholder' : 'Email'})
			}

	# Enforces unique emails for accounts
	def clean_email(self):
		email = self.cleaned_data.get('email')
		username = self.cleaned_data.get('username')
		if email and User.objects.filter(email = email).exclude(username = username).count():
			raise forms.ValidationError('This Email is already in the system.')
		return email

	def clean_password(self):
		return password_check(self)

class PasswordResetForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('password',)
		widgets = {'password' : forms.PasswordInput(attrs = {'placeholder' : 'New Password'})}

	def clean_password(self):
		return password_check(self)

# Function that checks the password based on certain parameters
def password_check(form):
	password = form.cleaned_data.get('password')
	if len(password) < 8:
		raise forms.ValidationError('Password eight characters or more.')
	return password

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('status', 'display_picture')

Sunami-Django-Old/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from accounts.models import UserProfile
from accounts.forms import UserForm, PasswordResetForm
from django.core.mail import send_mail

import random
import string

# Login required wrapper for as_view method for class views
# May be needed later
#class LoginRequiredMixin(object):
#	@classmethod
#	def as_view(cls, **initkwargs):
#		view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
#		return login_required(view)

###############################
# WRITE TESTS FOR ALL OF THIS #
###############################

# Class to login to user profile
# Write tests for this
class LoginView(View):
	def get(self, request):
		# If user already logged in, redirect to home page
		if request.user.is_authenticated():
			return redirect('index')

		return render(request, 'accounts/login.html', {'page_title' : 'Sunami - Login'})

	def post(self, request):
		errors = []

		email = request.POST.get('email')
		password = request.POST.get('password')

		# Find username based on email address given
		username = ''

		try:
			username = User.objects.get(email = email).username
		except:
			errors.append('This Email does not exist')

		user = authenticate(username = username, password = password)

		# If user could be found, login user
		if user:

			# If user is active, send back to homepage logged in
			if user.is_active:
				login(request, user)
				return redirect('index')

			else:
				errors.append('Account is inactive')

		else:
			errors.append('Password does not match Email')

		return render(request, 'accounts/login.html', {'errors' : errors[0:1], 'page_title' : 'Sunami - Login'})


# Class to logout and redirect 
class LogoutView(View):
	def get(self, request):
		logout(request)
		return redirect('index')

# Generate confirmation code
def generate_code():
	confirmation_code = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for i in range(33))
	return confirmation_code

################################
# Change to Async using Celery #
################################

# Send Registration Email
def send_registration_confirmation(user):
	profile = user.userprofile
	title = 'Sunami Account Confirmation'
	content = 'http://127.0.0.1:8000/profile/confirm/' + profile.confirmation_code + '/' + user.username
	send_mail(title, content, 'sunamisound@gmail.com', [user.email])

# Send Password Reset Email
def send_password_reset(user):
	profile = user.userprofile
	title = 'Sunami Password Reset'
	content = 'http://127.0.0.1:8000/profile/passreset/' + profile.confirmation_code + '/' + user.username
	send_mail(title, content, 'sunamisound@gmail.com', [user.email])

# Class to authenticate user
class ConfirmView(View):
	def get(self, request, confirmation_code, username):
		try:
			user = User.objects.get(username = username)
			profile = user.userprofile

			# Check if confirmation code is correct
			if profile.confirmation_code == confirmation_code:
				user.is_active = True
				user.save()
				return render(request, 'accounts/confirm.html', {'confirmed' : True, 
					'page_title' : 'Sunami - Account Confirmation'})

		except:
			pass

		# This is what shows up if the confirmation code is wrong
		return render(request, 'accounts/confirm.html', {'confirmed' : False, 
			'page_title' : 'Sunami - Accounts Confirmation'})

# Class to reset password
class IForgotView(View):
	def get(self, request):
		return render(request, 'accounts/iforgot.html', {'page_title' : 'Sunami - Password Reset'})

	def post(self, request):
		errors = []

		email = request.POST.get('email')

		# Find user
		user = None

		try:
			user = User.objects.get(email = email)
		except:
			errors.append('This Email does not exist')

		if user:
			profile = user.userprofile
			profile.confirmation_code = generate_code()
			profile.is_password_reset = True
			profile.save()

			if user.is_active:
				send_password_reset(user)
				return render(request, 'accounts/iforgot.html', {'errors' : errors[0:1], 'page_title' : 'Sunami - Password Reset', 'sent': True})

			else:
				errors.append('Account is inactive')

		return render(request, 'accounts/iforgot.html', {'errors' : errors[0:1], 'page_title' : 'Sunami - Password Reset'})

# Class to receive password reset
class PasswordResetView(View):
	def get(self, request, confirmation_code, username):
		try:
			user = User.objects.get(username = username)
			profile = user.userprofile

			# Check if the confirmation code is correct
			# Check if the user is active for reset
			if profile.is_password_reset and profile.confirmation_code == confirmation_code:
				password_reset_form = PasswordResetForm()

				return render(request, 'accounts/passreset.html', {'page_title' : 'Sunami - Password Reset', 'reset' : True, 
					'pass_form' : password_reset_form})

		except:
			pass

		return render(request, 'accounts/passreset.html', {'page_title' : 'Sunami - Password Reset'})

	def post(self, request, confirmation_code, username):
		changed = False

		try:
			user = User.objects.get(username = username)
			profile = user.userprofile

			# Just in case someone tries to break in
			if not profile.is_password_reset or profile.confirmation_code != confirmation_code:
				return render(request, 'accounts/passreset.html', {'page_title' : 'Sunami - Password Reset'})

			password_reset_form = PasswordResetForm(data = request.POST)

			if password_reset_form.is_valid():
				profile.is_password_reset = False
				profile.save()

				user.set_password(password_reset_form.cleaned_data.get('password'))
				user.save()

				changed = True

			return render(request, 'accounts/passreset.html', {'page_title' : 'Sunami - Password Reset', 
				'pass_form' : password_reset_form, 'changed' : changed, 'reset' : True})

		except:
			pass

		return render(request, 'accounts/passreset.html', {'page_title' : 'Sunami - Password Reset'})

# Class to register a new user profile
# Write tests for this
class SignUpView(View):
	def get(self, request):
		user_form = UserForm()

		return render(request, 'accounts/signup.html', {'user_form' : user_form, 'registered' : False, 
			'page_title' : 'Sunami - Sign Up'})

	def post(self, request):
		registered = False

		user_form = UserForm(data = request.POST)

		if user_form.is_valid():
			user = user_form.save()

			# Required to hash the password
			user.set_password(user.password)
			user.is_active = False
			user.save()

			# DateTimes automatically added in models.py
			profile = UserProfile(user = user, confirmation_code = generate_code())
			profile.save()

			send_registration_confirmation(user)

			registered = True

		else:
			print(user_form.errors)

		return render(request, 'accounts/signup.html', {'user_form' : user_form, 'registered' : registered, 
			'page_title' : 'Sunami - Sign Up'})

Sunami-Django-Old/templates/accounts/confirm.html
{% extends "base.html" %}

{% block header-block %}

<div id="headerwrap">
<div class="container">
<div class="row">

<div class="container">
    <div class="row">
        {% if confirmed %}
        <h3>YOUR ACCOUNT HAS BEEN CONFIRMED!</h3>
        {% else %}
        <h3>WTF MANNNNNN</h3>
        {% endif %}
    </div><! --/row -->
</div><! --/container -->

</div>
</div>
</div>

{% endblock %}

{% block main-block %}{% endblock %}

Sunami-Django-Old/templates/accounts/iforgot.html
{% extends "base.html" %}

{% block header-block %}

<div id="headerwrap">
<div class="container">
<div class="row">

<div class="container">
    <div class="row">
        {% if sent %}

            <h1 class="white-label">Fear Not</h1>
            <h5>Your email has been sent</h5>

        {% else %}

            <h1 class="white-label">Password Reset</h1>

            <div class="login-area">

                <h5>Enter your email and you will be saved</h5>

                <div class="error-area">
                    {% for error in errors %}
                    <i class="fa fa-exclamation-circle error-mark"></i> <li class="errorlist">{{ error }}</li>
                    {% endfor %}
                </div>

                <form role="form" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email" name="email" required>
                    </div>
                    <button type="submit" class="btn btn-theme">Reset</button>
                </form>

            </div>

        {% endif %}

    </div><! --/row -->
</div><! --/container -->

</div>
</div>
</div>

{% endblock %}

{% block main-block %}{% endblock %}

Sunami-Django-Old/templates/accounts/login.html
{% extends "base.html" %}

{% block header-block %}

<div id="headerwrap">
<div class="container">
<div class="row">

<div class="container">
    <div class="row">
        <h1 class="white-label">Login</h1>


        <div class="login-area">


        <!--<a href="#"><div class="fb-button"><h4>Login with <i class="fa fa-facebook fa-lg"></i>acebook</h4></div></a>

        <div class="hline-form"></div>-->

        <div class="error-area">
            {% for error in errors %}

            <i class="fa fa-exclamation-circle error-mark"></i> <li class="errorlist">{{ error }}</li>

            {% endfor %}
        </div>

        <form role="form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="email" class="form-control" placeholder="Email" name="email" required>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password" required>
            </div>

            <div class="login-tab"><a href="{% url "accounts:iforgot" %}">Forgot password?</a> | 
                <a href="{% url "accounts:signup" %}">Sign up</a><br></div>

            <button type="submit" class="btn btn-theme">Login</button>
        </form>

    </div>

    </div><! --/row -->
</div><! --/container -->

</div>
</div>
</div>

{% endblock %}

{% block main-block %}{% endblock %}

Sunami-Django-Old/templates/accounts/passreset.html
{% extends "base.html" %}

{% load formtags %}

{% block header-block %}

<div id="headerwrap">
<div class="container">
<div class="row">

<div class="container">
    <div class="row">
        {% if changed %}

            <h1 class="white-label">Good Job</h1>
            <h5>You have successfully changed your password</h5>

        {% else %}

            {% if reset %}
                <h1 class="white-label">Password Reset</h1>

                <div class="login-area">
                    <h5>Enter your new password</h5>

                    {% if pass_form.password.errors %}
                        <i class="fa fa-exclamation-circle error-mark"></i> {{ pass_form.password.errors }}
                    {% endif %}
            
                    <form role="form" method="post">
                    {% csrf_token %}
                    
                    {% for field in pass_form %}

                    <div class="form-group">
                        {{ field | add_attributes:'class=form-control,required' }} 
                    </div>

                    {% endfor %}

                    <button type="submit" class="btn btn-theme">Reset Password</button>

                	</form>
                </div>
            {% else %}
                <h3>WTF MANNNNNN</h3>
            {% endif %}

        {% endif %}
    </div><! --/row -->
</div><! --/container -->

</div>
</div>
</div>

{% endblock %}

{% block main-block %}{% endblock %}

Sunami-Django-Old/templates/accounts/signup.html
{% extends "base.html" %}

{% load formtags %}

{% block header-block %}

<div id="headerwrap">
<div class="container">
<div class="row">

<div class="container">
    <div class="row">

        {% if registered %}

            <h1 class="white-label">Thank You for Signing Up</h1>
            <h5>A confirmation email has been sent to you</h5>

        {% else %}

            <h1 class="white-label">Sign Up</h1>

            <div class="login-area">

                <!--<a href="#"><div class="fb-button"><h4>Login with <i class="fa fa-facebook fa-lg"></i>acebook</h4></div></a>

                <div class="hline-form"></div>-->

                {% if user_form.username.errors %}
                    <i class="fa fa-exclamation-circle error-mark"></i> {{ user_form.username.errors }}
                {% elif user_form.email.errors %}
                    <i class="fa fa-exclamation-circle error-mark"></i> {{ user_form.email.errors }}
                {% elif user_form.password.errors %}
                    <i class="fa fa-exclamation-circle error-mark"></i> {{ user_form.password.errors }}
                {% endif %}
        
                   <form role="form" method="post">
                    {% csrf_token %}
                    
                    {% for field in user_form %}

                    <div class="form-group">
                        {{ field | add_attributes:'class=form-control,required' }} 
                    </div>

                    {% endfor %}

                    <button type="submit" class="btn btn-theme">Sign Up</button>

                </form>

            </div>

        {% endif %}

    </div><! --/row -->
 </div><! --/container -->

<!-- St.Patty's Day 2015 -->
<!-- A night to remember -->

</div>
</div>
</div>

{% endblock %}

{% block main-block %}{% endblock %}